name: Deploy to Server

on:
  push:
    branches:
      - main
      - 'feature/code-cleanup'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            whoami
            echo "Deploying on $(whoami)@${{ secrets.SERVER_IP }}"

            # 1. Navigate to the project directory
            cd ~/sheriff_project/movie-archive
            pwd

            # 2. Pull the latest code
            git pull origin main

            ls -la

            # 3. Install dependencies, using ci for faster installation
            npm install
            npm audit

            # 4. Restart your Node.js application (assuming using PM2 or Node directly)
            pm2 restart index.js || pm2 start index.js --name movie-archive